# @package _global_
defaults:
  # c.f. https://hydra.cc/docs/patterns/configuring_experiments/
  - /jobs/eval_reasoning_dlc@jobs

client:
  api_base: "http://localhost:8000/v1"
  model: "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"
