repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.11.3"
    hooks:
      - id: ruff
        args: ["--fix", "--show-fixes"]
      - id: ruff-format


  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.15.0"
    hooks:
      - id: mypy
        files: src|tests
        args: []
        additional_dependencies:
          - hydra-core
          - omegaconf

  # https://github.com/srstevenson/nb-clean?tab=readme-ov-file#cleaning-pre-commit-hook
  - repo: https://github.com/srstevenson/nb-clean
    rev: 4.0.1
    hooks:
      - id: nb-clean
        args:
          - --remove-empty-cells
          # https://github.com/srstevenson/nb-clean?tab=readme-ov-file#preserving-all-nbformat-metadata
          - --preserve-cell-metadata
          - collapsed
          - scrolled
          - deletable
          - editable
          - format
          - name
          - tags
          - jupyter
          - execution
          - --preserve-cell-outputs
          # - --preserve-execution-counts
          - --preserve-notebook-metadata
          - --
