[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "metagen"
version = "0.0.1"
dependencies = [
    "hydra-core", # NOTE: not "hydra"!
    "omegaconf",
]

[project.optional-dependencies]
dev = [
    "ruff",
    "mypy"
]

[tool.setuptools]
package-dir = {"" = "src"}