[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "metagen"
version = "0.1.0"
dependencies = [
    "hydra-core", # NOTE: not "hydra"!
    "omegaconf",
]

[tool.setuptools]
package-dir = {"" = "src"}