# @package _global_

jobs:
  latex_or_expr_answer:
    input:
      glob_pattern: "./data/metagen-runs/*cot_boxed_qa*/metagen-records.jsonl"
      filter_for_regex_pattern: "^(?!.*mmlu).*$"
    pred_extraction_configs:
      - extraction_type: LATEX
      - extraction_type: EXPR
    add_boxed_to_gold: true
    gold_extraction_configs:
      - extraction_type: LATEX
  string_answer:
    input:
      glob_pattern: "./data/metagen-runs/*mmlu*/metagen-records.jsonl"
    pred_extraction_configs:
      - extraction_type: LATEX # For \boxed{...}
      - extraction_type: STRING
        kwargs:
          strings: ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"]
    add_boxed_to_gold: false
    gold_extraction_configs:
      - extraction_type: STRING
        kwargs:
          strings: ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"]
